receiving weather data  + networking with Alamofire
RomanKozlovskiy/TasksApp pull request #3
Opened 2024-04-11 08:21 UTC by RomanKozlovskiy

added Weather module with a request to receive weather data

2024-04-12 13:12 UTC, bguchinov requested changes

2024-04-12 13:12 UTC, bguchinov commented on TasksApp/TasksApp/ViewControllers/TasksViewControllers/WeatherModule/Models/WeatherInfo.swift
> +    var currentTempDescription: String {
вот эти свитчи точно лучше заменить util функцией, которая будет менять склонение в зависимости от числа которое придет, то есть ты даешь список слов склоняемых градус, градуса, градусов, и она подставляет то которое надо по числу

2024-04-12 13:12 UTC, bguchinov commented on TasksApp/TasksApp/ViewControllers/TasksViewControllers/WeatherModule/WeatherNetworkService/WeatherNetworkManager.swift
> +    private var yandexAccessKeyValue: String {
А почему это переменные а не консты, разве baseURL или AccessKey могут поменяться в рантайме?

2024-04-15 10:06 UTC, RomanKozlovskiy commented on TasksApp/TasksApp/ViewControllers/TasksViewControllers/WeatherModule/WeatherNetworkService/WeatherNetworkManager.swift
> +    private var yandexAccessKeyValue: String {
Так как они являются вычисляемыми свойствами они не могут быть константами. Так как URL адрес и accessKey я храню в файле .plist с помощью вычисляемых свойств удобно доставать эти значения и так же они гарантируют то, что мы не может присвоить в них какое-либо другое значение. Можно было бы создать структуру по формированию URL адреса, но я посчитал, что для данной реализации можно сделать более просто. Если такое решение не самое лучшее, я могу переписать.

2024-04-15 10:53 UTC, bguchinov approved these changes

2024-04-15 11:20 UTC, merged